// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyAfJGbytzuxy99i2uJNdawoX4mV3OXzzSI",
    authDomain: "fluttertechnical.firebaseapp.com",
    projectId: "fluttertechnical",
    storageBucket: "fluttertechnical.firebasestorage.app",
    messagingSenderId: "175524284438",
    appId: "1:175524284438:web:26257abb961d092a828d37",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGz7Fri9AafTbQ1_kIOC9IKPXM176UkHs',
    appId: '1:175524284438:android:d95bc1f16028c56c828d37',
    messagingSenderId: '175524284438',
    projectId: 'fluttertechnical',
    storageBucket: 'fluttertechnical.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjXUV1bapl5-J4rOgdv5sRSYSiNJjpYgM',
    appId: '1:175524284438:ios:8b05985b07609a7f828d37',
    messagingSenderId: '175524284438',
    projectId: 'fluttertechnical',
    storageBucket: 'fluttertechnical.firebasestorage.app',
    iosBundleId: 'com.example.technicaltest',
  );
}
